#!/usr/bin/env bash
set -e

# build_ai_stack.sh
# Creates a comprehensive Python AI project tree with integrations for:
# experta, sympy, networkx, transitions, scikit-learn, numpy, pandas,
# rapidfuzz, spacy, faiss-cpu, pydantic, langgraph (optional), APScheduler,
# pytest, markovify, rank_bm25 and supporting modules (sqlite memory, sandboxing, scheduler).
#
# Usage: run from the repository root:
#   bash build_ai_stack.sh
# Then: cd ai_stack && pip install -r requirements.txt
# Note: faiss-cpu installation may vary by platform. The script adds guidance.

INFO(){ echo -e "\033[96m$1\033[0m"; }
OK(){ echo -e "\033[92m$1\033[0m"; }
WARN(){ echo -e "\033[93m$1\033[0m"; }
ERR(){ echo -e "\033[91m$1\033[0m"; }

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
AI_DIR="$ROOT_DIR/ai_stack"
CORE_DIR="$AI_DIR/core"
TESTS_DIR="$AI_DIR/tests"
DATA_DIR="$AI_DIR/data"
NOTEBOOKS_DIR="$AI_DIR/notebooks"
MODELS_DIR="$AI_DIR/models"

if [ -d "$AI_DIR" ]; then
    WARN "Existing ai_stack/ detected — backing up to ai_stack.bak"
    rm -rf "$AI_DIR.bak" || true
    mv "$AI_DIR" "$AI_DIR.bak"
fi

mkdir -p "$CORE_DIR" "$TESTS_DIR" "$DATA_DIR" "$NOTEBOOKS_DIR" "$MODELS_DIR"

INFO "Creating project structure under $AI_DIR"

# requirements.txt with pinned (stable) versions (as of search)
cat > "$AI_DIR/requirements.txt" << 'REQ'
experta==1.9.3
sympy==1.14.0
networkx==3.4
transitions==0.9.1
scikit-learn==1.9.0
numpy==2.5.2
pandas==3.0.5
rapidfuzz==3.6.2
spacy==3.7.4
faiss-cpu==1.8.0
pydantic==2.7.1
langgraph==0.0.63
APScheduler==3.10.4
pytest==8.2.2
markovify==0.10.0
rank_bm25==0.2.2
# Optional helper libs
tqdm>=4.0.0
python-dotenv>=0.21.0
REQ
OK "requirements.txt"

# top-level README
cat > "$AI_DIR/README.md" << 'MD'
# AI Stack — Comprehensive Local AI Toolkit

This folder (`ai_stack/`) is generated by `build_ai_stack.sh`. It contains starter modules integrating symbolic reasoning, knowledge graphs, ML utilities, vector search, scheduler, and memory persistence, with a design that allows you to approximate deep reasoning without requiring remote LLM calls.

See `core/` for component stubs and `tests/` for basic tests.

To install dependencies:

  cd ai_stack
  pip install -r requirements.txt

Note on `faiss-cpu`: on some platforms pip wheel may not be available. If installation fails, consult Faiss docs or install from conda.

MD
OK "README.md"

# .gitignore
cat > "$AI_DIR/.gitignore" << 'GI'
__pycache__/
*.pyc
.venv/
.env
models/
data/
AI_DIR.bak/
GI
OK ".gitignore"

# core/__init__.py
cat > "$CORE_DIR/__init__.py" << 'PY'
# core package for ai_stack
__all__ = [
    'rule_engine', 'symbolic_engine', 'state_machine', 'ml_utils', 'ner_spacy',
    'sql_memory', 'vector_index', 'scheduler', 'workflow_orchestrator', 'sandbox'
]
PY
OK "core/__init__.py"

# core/rule_engine.py — experta based starter
cat > "$CORE_DIR/rule_engine.py" << 'PY'
# -*- coding: utf-8 -*-
"""
rule_engine.py — A small wrapper around experta to define and run rules.
"""
try:
    from experta import KnowledgeEngine, Fact, Rule, MATCH
except Exception:
    KnowledgeEngine = None
    Fact = object
    Rule = object

class SimpleFact(Fact):
    """Generic fact container"""
    pass

class RuleEngine:
    def __init__(self):
        if KnowledgeEngine is None:
            raise RuntimeError('experta is not installed')
        self.engine = KnowledgeEngine()

    def reset(self):
        self.engine.reset()

    def declare(self, **kwargs):
        self.engine.declare(SimpleFact(**kwargs))

    def run(self):
        self.engine.run()

# Example rule definitions should be added by the integrator using experta's APIs.
PY
OK "core/rule_engine.py"

# core/symbolic_engine.py — sympy utilities
cat > "$CORE_DIR/symbolic_engine.py" << 'PY'
# -*- coding: utf-8 -*-
"""
symbolic_engine.py — helpers for symbolic math/logic via sympy
"""
try:
    import sympy as sp
except Exception:
    sp = None

def simplify_expression(expr_str):
    if sp is None:
        return expr_str
    try:
        expr = sp.sympify(expr_str)
        return str(sp.simplify(expr))
    except Exception:
        return expr_str

# Simple boolean satisfiability check for small logical expressions
def is_satisfiable(expr_str):
    if sp is None:
        return None
    try:
        expr = sp.sympify(expr_str)
        return sp.simplify_logic(expr) is not None
    except Exception:
        return None
PY
OK "core/symbolic_engine.py"

# core/state_machine.py — transitions
cat > "$CORE_DIR/state_machine.py" << 'PY'
# -*- coding: utf-8 -*-
"""
state_machine.py — Pet states using transitions
"""
try:
    from transitions import Machine
except Exception:
    Machine = None

STATES = [
    'idle', 'listening', 'reasoning', 'planning', 'executing', 'dreaming', 'sleep'
]

class PetStateMachine:
    def __init__(self, model=None):
        self.model = model or object()
        if Machine is None:
            raise RuntimeError('transitions not installed')
        self.machine = Machine(model=self.model, states=STATES, initial='idle')
        self.machine.add_transition('hear', 'idle', 'listening')
        self.machine.add_transition('reason', 'listening', 'reasoning')
        self.machine.add_transition('plan', 'reasoning', 'planning')
        self.machine.add_transition('exec', 'planning', 'executing')
        self.machine.add_transition('finish', 'executing', 'idle')
        self.machine.add_transition('dream', '*', 'dreaming')
        self.machine.add_transition('wake', 'dreaming', 'idle')
PY
OK "core/state_machine.py"

# core/ml_utils.py — sklearn wrappers
cat > "$CORE_DIR/ml_utils.py" << 'PY'
# -*- coding: utf-8 -*-
"""
ml_utils.py — helpers for classic ML using scikit-learn, numpy, pandas
- clustering, lightweight reranker (online SGD), tfidf vectorizer
"""
try:
    import numpy as np
    import pandas as pd
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.cluster import MiniBatchKMeans
    from sklearn.linear_model import SGDClassifier
except Exception:
    np = None
    pd = None

class SimpleReranker:
    def __init__(self):
        self.model = None
        self.vec = None

    def fit(self, texts, labels):
        if pd is None:
            return
        self.vec = TfidfVectorizer(max_features=2000)
        X = self.vec.fit_transform(texts)
        self.model = SGDClassifier(max_iter=1000)
        self.model.fit(X, labels)

    def predict_score(self, query, candidates):
        if self.model is None or self.vec is None:
            return [(c, 0.0) for c in candidates]
        qv = self.vec.transform([query])
        X = self.vec.transform(candidates)
        scores = self.model.decision_function(X)
        return list(zip(candidates, scores))

class TopicCluster:
    def __init__(self, k=8):
        self.k = k
        self.vec = None
        self.km = None

    def fit(self, texts):
        if pd is None:
            return
        self.vec = TfidfVectorizer(max_features=3000)
        X = self.vec.fit_transform(texts)
        self.km = MiniBatchKMeans(n_clusters=self.k)
        self.km.fit(X)

    def predict(self, texts):
        if self.km is None:
            return [0]*len(texts)
        X = self.vec.transform(texts)
        return self.km.predict(X)
PY
OK "core/ml_utils.py"

# core/ner_spacy.py — spaCy NER helper with fallback
cat > "$CORE_DIR/ner_spacy.py" << 'PY'
# -*- coding: utf-8 -*-
"""
ner_spacy.py — spaCy based entity extraction with lightweight fallback
"""
try:
    import spacy
    NLP = None
    # attempt to load small en model; for Vietnamese user may need a custom model
    try:
        NLP = spacy.load('en_core_web_sm')
    except Exception:
        try:
            NLP = spacy.blank('en')
        except Exception:
            NLP = None
except Exception:
    spacy = None
    NLP = None

import re
_TOKEN_RE = re.compile(r"[^\W\d_]+", re.UNICODE)

def extract_entities(text):
    if NLP:
        doc = NLP(text)
        ents = [ent.text for ent in doc.ents]
        if ents:
            return ents
    # fallback: capitalize-word heuristics
    words = _TOKEN_RE.findall(text)
    caps = [w for w in words if w.istitle()]
    return list(dict.fromkeys(caps))
PY
OK "core/ner_spacy.py"

# core/sql_memory.py — sqlite3 with pydantic schemas
cat > "$CORE_DIR/sql_memory.py" << 'PY'
# -*- coding: utf-8 -*-
"""
sql_memory.py — Simple persistent memory using sqlite3 and pydantic for schema
"""
import sqlite3, json, os
try:
    from pydantic import BaseModel
except Exception:
    BaseModel = None

DB_NAME = os.path.join(os.path.dirname(__file__), '..', 'data', 'memory.db')

class DocumentSchema(BaseModel if BaseModel else object):
    id: int
    text: str
    source: str = ''
    weight: float = 1.0

class SQLMemory:
    def __init__(self, db_path=None):
        self.db_path = db_path or DB_NAME
        os.makedirs(os.path.dirname(self.db_path), exist_ok=True)
        self.conn = sqlite3.connect(self.db_path, check_same_thread=False)
        self._ensure()

    def _ensure(self):
        cur = self.conn.cursor()
        cur.execute('''CREATE TABLE IF NOT EXISTS documents (id INTEGER PRIMARY KEY, text TEXT, source TEXT, weight REAL)''')
        cur.execute('''CREATE TABLE IF NOT EXISTS feedback (id INTEGER PRIMARY KEY AUTOINCREMENT, doc_id INTEGER, sentiment INTEGER, ts INTEGER)''')
        self.conn.commit()

    def add_document(self, doc):
        cur = self.conn.cursor()
        cur.execute('INSERT OR REPLACE INTO documents (id, text, source, weight) VALUES (?,?,?,?)',
                    (doc.get('id'), doc.get('text'), doc.get('source'), doc.get('weight',1.0)))
        self.conn.commit()

    def get_top(self, limit=10):
        cur = self.conn.cursor()
        cur.execute('SELECT id, text, source, weight FROM documents ORDER BY weight DESC LIMIT ?', (limit,))
        return cur.fetchall()

    def add_feedback(self, doc_id, sentiment):
        cur = self.conn.cursor()
        cur.execute('INSERT INTO feedback (doc_id, sentiment, ts) VALUES (?,?,strftime("%s","now"))', (doc_id, sentiment))
        self.conn.commit()
PY
OK "core/sql_memory.py"

# core/vector_index.py — faiss-cpu wrapper and tfidf fallback
cat > "$CORE_DIR/vector_index.py" << 'PY'
# -*- coding: utf-8 -*-
"""
vector_index.py — Wrapper to use FAISS (if available) or TF-IDF + sklearn nearest
"""
try:
    import faiss
    HAS_FAISS = True
except Exception:
    HAS_FAISS = False

try:
    from sklearn.feature_extraction.text import TfidfVectorizer
    import numpy as np
except Exception:
    TfidfVectorizer = None
    np = None

class VectorIndex:
    def __init__(self, dim=128):
        self.dim = dim
        self.index = None
        self.texts = []
        self.vec = None

    def build_tfidf(self, texts):
        if TfidfVectorizer is None:
            raise RuntimeError('sklearn not installed')
        self.texts = texts
        self.vec = TfidfVectorizer(max_features=self.dim)
        X = self.vec.fit_transform(texts).astype('float32')
        if HAS_FAISS:
            import numpy as _np
            Xnp = _np.array(X.todense(), dtype='float32')
            self.index = faiss.IndexFlatIP(self.dim)
            self.index.add(Xnp)
        else:
            self.index = X

    def query(self, q, topk=5):
        if self.vec is None:
            return []
        qv = self.vec.transform([q]).astype('float32')
        if HAS_FAISS:
            import numpy as _np
            qnp = _np.array(qv.todense(), dtype='float32')
            D, I = self.index.search(qnp, topk)
            return [(self.texts[i], float(D[0][k])) for k, i in enumerate(I[0])]
        else:
            import numpy as _np
            from sklearn.metrics.pairwise import cosine_similarity
            sims = cosine_similarity(qv, self.index)[0]
            idx = sims.argsort()[::-1][:topk]
            return [(self.texts[i], float(sims[i])) for i in idx]
PY
OK "core/vector_index.py"

# core/scheduler.py — APScheduler starter
cat > "$CORE_DIR/scheduler.py" << 'PY'
# -*- coding: utf-8 -*-
"""
scheduler.py — background jobs using APScheduler
"""
try:
    from apscheduler.schedulers.background import BackgroundScheduler
except Exception:
    BackgroundScheduler = None

class JobScheduler:
    def __init__(self):
        if BackgroundScheduler is None:
            raise RuntimeError('APScheduler not installed')
        self.sched = BackgroundScheduler()
        self.sched.start()

    def add_interval(self, func, seconds=60):
        self.sched.add_job(func, 'interval', seconds=seconds)

    def shutdown(self):
        self.sched.shutdown()
PY
OK "core/scheduler.py"

# core/workflow_orchestrator.py — placeholder for langgraph or custom workflows
cat > "$CORE_DIR/workflow_orchestrator.py" << 'PY'
# -*- coding: utf-8 -*-
"""
workflow_orchestrator.py — simple orchestrator and hook for langgraph if installed
"""
try:
    import langgraph
    HAS_LANGGRAPH = True
except Exception:
    HAS_LANGGRAPH = False

class WorkflowOrchestrator:
    def __init__(self):
        self.has_langgraph = HAS_LANGGRAPH

    def run_pipeline(self, steps, context=None):
        context = context or {}
        for step in steps:
            func = step.get('func')
            args = step.get('args', [])
            kwargs = step.get('kwargs', {})
            if callable(func):
                try:
                    res = func(*args, **kwargs)
                    context[step.get('name','last')] = res
                except Exception as e:
                    context['error'] = str(e)
                    break
        return context
PY
OK "core/workflow_orchestrator.py"

# core/sandbox.py — subprocess sandbox helper
cat > "$CORE_DIR/sandbox.py" << 'PY'
# -*- coding: utf-8 -*-
"""
sandbox.py — run subprocesses with resource/time limits (best-effort)
"""
import subprocess, threading, os, sys

def run_with_timeout(cmd, timeout=5):
    proc = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    timer = threading.Timer(timeout, proc.kill)
    try:
        timer.start()
        out, err = proc.communicate()
        return proc.returncode, out.decode('utf-8', errors='ignore'), err.decode('utf-8', errors='ignore')
    finally:
        timer.cancel()
PY
OK "core/sandbox.py"

# tests/test_imports.py
cat > "$TESTS_DIR/test_imports.py" << 'PY'
def test_core_imports():
    import importlib
    modules = [
        'core.rule_engine','core.symbolic_engine','core.state_machine','core.ml_utils',
        'core.ner_spacy','core.sql_memory','core.vector_index','core.scheduler'
    ]
    for m in modules:
        importlib.import_module(m)
PY
OK "tests/test_imports.py"

# top-level helper script to run simple smoke test
cat > "$AI_DIR/run_smoke.sh" << 'SH'
#!/usr/bin/env bash
set -e
cd "$(dirname "$0")"
python - <<'PY'
from core.vector_index import VectorIndex
print('VectorIndex import OK')
from core.sql_memory import SQLMemory
m = SQLMemory()
print('SQLMemory OK — DB at', m.db_path)
PY
SH
chmod +x "$AI_DIR/run_smoke.sh"
OK "run_smoke.sh"

# final instructions
cat > "$AI_DIR/USAGE.md" << 'MD'
Quick usage
-----------
1) Install requirements (virtualenv recommended):
   python -m venv .venv
   source .venv/bin/activate
   pip install -r requirements.txt

2) Run smoke test:
   bash run_smoke.sh

3) Start integrating components into your main Pet brain (wire SQLMemory, VectorIndex, RuleEngine etc.)

Notes:
- faiss-cpu may require platform-specific installation. If pip install fails, consider conda: conda install -c pytorch faiss-cpu
- spaCy may need language model downloads: e.g., python -m spacy download en_core_web_sm
MD
OK "USAGE.md"

# Make project dir executable marker
chmod -R a+rX "$AI_DIR"

OK "Done. AI stack skeleton created at $AI_DIR"

INFO "Review files and run: cd ai_stack && pip install -r requirements.txt"

